# -*- coding: utf-8 -*-
"""Building_KB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y14CE1187PunC5DlSpXniwhcC553Xl9h

# <span style="color:blue"> Building Knowledge Base</span>
"""

!pip install openai
import openai
!pip install python-dotenv
import dotenv
!pip3 install pinecone-client
!pip install PyPDF2
from PyPDF2 import PdfReader
import re
import os
import json
import pinecone
from dotenv import load_dotenv
load_dotenv()
pinecone_api_key = os.getenv("PINECONE_API_KEY")
openai.api_key = os.getenv("OPENAI_API_KEY")
embed_model = "text-embedding-ada-002"
index_name = 'cstugpt-kb'
# initialize connection to pinecone (get API key at app.pinecone.io)
pinecone.init(
    api_key=pinecone_api_key,
    environment="us-west1-gcp-free" # The environment value could be found at Pinecone website, once created
)
index = pinecone.Index(index_name)
def mls_upsert(cstu_file, index_name, name_space, cstu_id, chunk_size, stride):
   # create a reader object
    print("Knowledge base file name:", cstu_file)
    reader = PdfReader(cstu_file)
    page_len = len(reader.pages)
    print("length of the knowledge base file:", page_len)
    doc = ""
    for i in range(page_len):
        doc += reader.pages[i].extract_text()
        print("page completed:", i)
    doc = doc.splitlines()
    print("The total lines: ", len(doc))

    #Connect to Pinecone index
    index = pinecone.Index(index_name)
    count = 0
    for i in range(0, len(doc), chunk_size):#The loop iterates over the document in steps of chunk_size
        #find begining and end of the chunk
        i_begin = max(0, i-stride)
        i_end = min(len(doc), i_begin+chunk_size)
        doc_chunk = doc[i_begin:i_end]
        print("-------------------------------------------------------------")
        print("The ", i//chunk_size + 1, " doc chunk text:", doc_chunk)
        texts = ""
        for x in doc_chunk:
            texts += x
        print("Texts:", texts)

        #Create embeddings of the chunk texts
        try:
            res = openai.Embedding.create(input=texts, engine=embed_model)
        except:
            done = False
            while not done:
                sleep(5)
                try:
                    res = openai.Embedding.create(input=texts, engine=embed_model)
                    done = True
                except:
                    pass
        embed = res['data'][0]['embedding']
        print("Embeds length:", len(embed))

        # Meta data preparation
        metadata = {
            "cstu_id": cstu_id + '_' + str(count),
            "text": texts
        }
        count += 1
        print("Upserted vector count is: ", count)
        print("==========================================================")

        #upsert to pinecone and corresponding namespace
        index.upsert(vectors=[(metadata["cstu_id"], embed, metadata)], namespace=name_space)

mls_upsert(r"cstugpt_kb.pdf", "cstugpt-kb", "cstu","cstu-kb", 8, 1)
mls_upsert(r"cstugpt_qa.pdf", "cstugpt-kb", "cstu","cstu-qa", 3, 1)

index.describe_index_stats()